Repository monoDriveIO/monodrive-client, pull requests merged in 2020-06, with the labels that each got.

#30 Dynamically determine vehicle name for ROS
  .vscode/launch.json
  examples/ros/src/vehicle_control/src/vehicle_control.cpp
Labels: bug

#31 Updating development with master
  .vscode/launch.json
  LICENSE
  examples/ros/src/vehicle_control/src/vehicle_control.cpp
  monodrive/core/src/ApiMessage.cpp
  monodrive/core/src/ApiMessage.h
  monodrive/core/src/Buffer.h
  monodrive/core/src/Configuration.cpp
  monodrive/core/src/Configuration.h
  monodrive/core/src/DataFrame.cpp
  monodrive/core/src/DataFrame.h
  monodrive/core/src/DataFramePrimitives.cpp
  monodrive/core/src/DataFramePrimitives.h
  monodrive/core/src/Jobs.cpp
  monodrive/core/src/Jobs.h
  monodrive/core/src/JsonHelpers.cpp
  monodrive/core/src/JsonHelpers.h
  monodrive/core/src/LaneSpline.h
  monodrive/core/src/Sensor.cpp
  monodrive/core/src/Sensor.h
  monodrive/core/src/SharedMemory.h
  monodrive/core/src/Simulator.cpp
  monodrive/core/src/Simulator.h
  monodrive/core/src/SimulatorCommands.h
  monodrive/core/src/Stopwatch.h
  monodrive/core/src/UECompatability.h
  monodrive/core/src/command_config.h
  monodrive/core/src/config_types.h
  monodrive/core/src/mono_ex.h
  monodrive/core/src/sensor_config.h
Labels: enhancement

#28 Implemented a simple config export to JSON
  .gitignore
  examples/cpp/dev/CMakeLists.txt
  examples/cpp/dev/config_export.cpp
Labels: enhancement

#33 Updated README with correct boost instructions
  README.md
Labels: bug, documentation

#40 Update README.md
  README.md
Labels: invalid

#41 Update README.md
  README.md
Labels: bug
