Repository monoDriveIO/monodrive-client, pull requests merged in 2020-09, with the labels that each got.

#92 Add CMake install to README
  README.md
Labels: bug, documentation

#93 Add CMake install to README
  README.md
Labels: bug, documentation

#94 Fisheye vignette
  examples/cpp/dev/fisheye_camera.cpp
  monodrive/core/src/sensor_config.h
Labels: enhancement

#98 fixed ros example, the keys are the initial names sent from scenario,…
  examples/ros/src/vehicle_control/src/vehicle_control.cpp
Labels: bug

#86 Update simulator config
  examples/config/scenarios/pilot_example.json
  examples/config/scenarios/scenario_example.json
  examples/config/simulator.json
  examples/config/simulator_no_traffic.json
  monodrive/matlab/configurations/simulator.json
  monodrive/matlab/configurations/simulator_closed_loop.json
  monodrive/matlab/configurations/simulator_config.json
Labels: bug, enhancement
