Repository monoDriveIO/monodrive-client, pull requests merged in 2020-07, with the labels that each got.

#34 Improved support for installation to external projects
  CMakeLists.txt
  README.md
  WORKSPACE
  examples/cpp/dev/CMakeLists.txt
  examples/cpp/lane_follower/CMakeLists.txt
  examples/cpp/replay/CMakeLists.txt
  examples/cpp/replay_step/CMakeLists.txt
  monodrive/core/BUILD
  monodrive/core/CMakeLists.txt
  monodrive/core/src/ApiMessage.h
  monodrive/core/src/Configuration.cpp
  monodrive/core/src/Configuration.h
  monodrive/core/src/DataFrame.cpp
  monodrive/core/src/DataFramePrimitives.cpp
  monodrive/core/src/Jobs.cpp
  monodrive/core/src/Jobs.h
  monodrive/core/src/JsonHelpers.h
  monodrive/core/src/Sensor.h
  monodrive/core/src/json.hpp
  monodrive/core/src/sensor_config.h
Labels: apollo, enhancement

#57 Added an example that uses the new autopilot command
  examples/cpp/dev/CMakeLists.txt
  examples/cpp/dev/autopilot_control.cpp
Labels: enhancement

#58 Name for the ego vehicle has to match the name on the scenario. Remov…
  examples/ros/src/wheel_vehicle_control/src/wheel_vehicle_control.cpp
Labels: bug

#55 Waypoint Sensor data structure reorganization / left+right waypoints
  examples/cpp/dev/CMakeLists.txt
  examples/cpp/dev/waypoint_sensor.cpp
  examples/ros/src/vehicle_control/src/vehicle_control.cpp
  monodrive/core/src/DataFramePrimitives.cpp
  monodrive/core/src/DataFramePrimitives.h
  monodrive/ros/src/monodrive_msgs/CMakeLists.txt
  monodrive/ros/src/monodrive_msgs/msg/ActorLane.msg
  monodrive/ros/src/monodrive_msgs/msg/ActorWaypoints.msg
Labels: bug, enhancement

#54 Update with latest state sensor and ROS fixes
  examples/cpp/dev/CMakeLists.txt
  examples/cpp/dev/waypoint_sensor.cpp
  examples/ros/src/simulator_control/src/simulator_control.cpp
  examples/ros/src/vehicle_control/src/vehicle_control.cpp
  examples/ros/src/wheel_vehicle_control/src/wheel_vehicle_control.cpp
  monodrive/core/src/DataFramePrimitives.cpp
  monodrive/core/src/DataFramePrimitives.h
  monodrive/ros/src/monodrive_msgs/CMakeLists.txt
  monodrive/ros/src/monodrive_msgs/msg/ActorLane.msg
  monodrive/ros/src/monodrive_msgs/msg/ActorWaypoints.msg
  monodrive/ros/src/monodrive_msgs/msg/VehicleState.msg
Labels: bug, enhancement

#63 Removed unused fields from waypoint
  monodrive/ros/src/monodrive_msgs/msg/Waypoint.msg
Labels: bug

#66 Remove left/right indicators from auto pilot
  examples/cpp/dev/autopilot_control.cpp
Labels: bug

#68 Added explicit warnings for missing config files
  monodrive/core/src/Configuration.cpp
  monodrive/core/src/Simulator.cpp
Labels: enhancement

#70 Added configuration and demo for waypoint debug
  examples/cpp/dev/waypoint_sensor.cpp
  monodrive/core/src/sensor_config.h
Labels: enhancement
